flask:
    PROPAGATE_EXCEPTIONS: True
    DEBUG: True
    LOG_LEVEL: debug

database:
    DBNAME: DBNAME
    USER: USERNAME
    HOST: localhost
    # PASSWORD: PASSWORD

uwsgi:
    master: true
    pythonpath: ~/src/pyris
    socket: localhost:8855
    module: pyris.api.wsgi:app
    processes: 1
    enable-threads: true
    protocol: uwsgi
    need-app: true
    catch: exceptions=true
    touch: reload=~/pyris-app.reload
    daemonize: /var/log/uwsgi/app/pyris.log
    env: PYRIS_APP_SETTINGS=~/src/pyris/app.yml
